"""FSM events and interrupts from fsm_events.yaml."""

from __future__ import annotations

from enum import Enum


class SessionProblemEvent(str, Enum):
    # Session -> Problem downward
    EVT_PROBLEM_READY = "EVT_PROBLEM_READY"
    EVT_SESSION_PAUSE = "EVT_SESSION_PAUSE"

    # Problem -> Session upward
    EVT_PROBLEM_DONE = "EVT_PROBLEM_DONE"
    EVT_ABORT_PROBLEM = "EVT_ABORT_PROBLEM"


class ProblemStepEvent(str, Enum):
    # Problem -> Step downward
    EVT_STEP_CONTEXT_READY = "EVT_STEP_CONTEXT_READY"
    EVT_STEP_RETRY = "EVT_STEP_RETRY"
    EVT_STEP_RECOVERY = "EVT_STEP_RECOVERY"

    # Step -> Problem upward
    EVT_ADVANCE_STEP = "EVT_ADVANCE_STEP"
    EVT_ROLLBACK_STEP = "EVT_ROLLBACK_STEP"
    EVT_BRANCH_PROPOSED = "EVT_BRANCH_PROPOSED"
    EVT_PROBLEM_COMPLETE = "EVT_PROBLEM_COMPLETE"
    EVT_ABORT_PROBLEM = "EVT_ABORT_PROBLEM"


class StepLocalEvent(str, Enum):
    EVT_STUDENT_REPLY = "EVT_STUDENT_REPLY"
    EVT_ROUTED_MISLEAD = "EVT_ROUTED_MISLEAD"
    EVT_ROUTED_CONCEPT = "EVT_ROUTED_CONCEPT"
    EVT_ROUTED_AFFECT = "EVT_ROUTED_AFFECT"
    EVT_ROUTED_ELICIT = "EVT_ROUTED_ELICIT"
    EVT_ROUTED_VERIFY = "EVT_ROUTED_VERIFY"
    EVT_ROUTED_ADVANCE = "EVT_ROUTED_ADVANCE"
    EVT_ROUTED_BAILOUT = "EVT_ROUTED_BAILOUT"
    EVT_ROUTED_DEFAULT = "EVT_ROUTED_DEFAULT"
    EVT_RECOVERY_READY = "EVT_RECOVERY_READY"
    EVT_CLARIFIED = "EVT_CLARIFIED"
    EVT_REFOCUSED = "EVT_REFOCUSED"
    EVT_OVERLOADED = "EVT_OVERLOADED"
    EVT_HINT_EXHAUSTED = "EVT_HINT_EXHAUSTED"
    EVT_VERIFY_PASS = "EVT_VERIFY_PASS"
    EVT_VERIFY_FAIL = "EVT_VERIFY_FAIL"
    EVT_DIRECT_DONE = "EVT_DIRECT_DONE"
    EVT_ROLLBACK_REQUEST = "EVT_ROLLBACK_REQUEST"
    EVT_MARK_AND_MOVE = "EVT_MARK_AND_MOVE"


class InterruptSignal(str, Enum):
    """Interrupt signals with highest-priority transition semantics."""

    EVT_SESSION_PAUSE = "EVT_SESSION_PAUSE"
    EVT_ABORT = "EVT_ABORT"
    EVT_ABORT_PROBLEM = "EVT_ABORT_PROBLEM"
    EVT_ROUTED_BAILOUT = "EVT_ROUTED_BAILOUT"
    EVT_STUDENT_REPLY = "EVT_STUDENT_REPLY"
